"""KRYPT Vault — persistent per-event session store + auto writeups.

Organises solves under CTF events (jeopardy-style). Each captured flag is saved
with its target, category, engine, timestamp, the full triage log, and a
generated markdown writeup so you can see exactly how the flag was captured.

Storage (JSON + markdown files, human-readable):
  ~/ctf-solver/vault/events.json
  ~/ctf-solver/vault/writeups/<solve_id>.md
"""
from __future__ import annotations

import datetime as dt
import json
import os
import re
import uuid

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VAULT = os.path.join(ROOT, "vault")
EVENTS = os.path.join(VAULT, "events.json")
WRITEUPS = os.path.join(VAULT, "writeups")


def _now() -> str:
    return dt.datetime.now().strftime("%Y-%m-%d %H:%M")


def _load() -> dict:
    try:
        with open(EVENTS) as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {"events": []}


def _save(data: dict) -> None:
    os.makedirs(VAULT, exist_ok=True)
    tmp = EVENTS + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(data, fh, indent=2, default=str)
    os.replace(tmp, EVENTS)


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (s or "event").lower()).strip("-") or "event"


def list_events() -> dict:
    """All events with their solves (newest event first)."""
    data = _load()
    data["events"].sort(key=lambda e: e.get("created", ""), reverse=True)
    return data


def ensure_event(name: str, event_id: str = "") -> dict:
    data = _load()
    name = (name or "Untitled Event").strip()
    for e in data["events"]:
        if (event_id and e["id"] == event_id) or e["name"].lower() == name.lower():
            return e
    ev = {"id": _slug(name) + "-" + uuid.uuid4().hex[:6], "name": name,
          "created": _now(), "solves": []}
    data["events"].append(ev)
    _save(data)
    return ev


def _title(t: dict) -> str:
    raw = t.get("raw") or "challenge"
    if t.get("kind") == "file":
        return os.path.basename(raw.rstrip("/")) or raw
    return raw


def make_writeup(res: dict, flag: str, event_name: str) -> str:
    """Generate a professional, deterministic CTF writeup (no LLM tokens used).

    Structure follows the standard high-quality format: title, metadata,
    challenge, TL;DR, approach (recon + the winning step with evidence), flag,
    tools, and takeaways.
    """
    t = res.get("target", {})
    steps = res.get("steps", [])
    cat = (t.get("subkind") or t.get("kind") or "misc")
    brief = (res.get("briefing") or "").strip()
    hits = [s for s in steps if s.get("flags")]
    win = hits[0] if hits else None

    md = [f"# {_title(t)}", "",
          f"> **{event_name}** · `{cat.upper()}` · captured {_now()}", ""]

    # Challenge
    md += ["## Challenge", ""]
    md.append(brief if brief else "_No description provided._")
    md += ["",
           f"- **Target:** `{t.get('raw','')}`",
           f"- **Type:** {t.get('kind','?')}"
           + (f" / {t.get('subkind')}" if t.get("subkind") else "")
           + (f" ({t.get('mime')})" if t.get("mime") else ""), ""]

    # TL;DR
    md += ["## TL;DR", ""]
    if win:
        md.append(f"Flag recovered via **`{win['step']}`** — {win.get('summary','')}.")
    else:
        md.append("See the approach below.")
    md += ["", f"> **Flag:** `{flag}`", ""]

    # Approach — recon then the winning move
    md += ["## Approach", "", "### 1. Reconnaissance", ""]
    recon = [s for s in steps if s.get("step") in
             ("file", "strings", "exiftool", "binwalk+entropy", "checksec",
              "readelf-header", "symbols", "7z-list", "headers", "banner",
              "preview", "briefing")][:5]
    if recon:
        for s in recon:
            md.append(f"- **{s['step']}** — {s.get('summary','')}")
    else:
        md.append("- Automated triage swept the target for the cheap wins.")
    md.append("")

    if win:
        md += [f"### 2. Capturing the flag — `{win['step']}`", "",
               win.get("summary", ""), ""]
        out = (win.get("output") or "").strip()
        if out:
            md += ["```", out[:2000], "```", ""]

    # Flag
    md += ["## Flag", "", "```", flag, "```", ""]

    # Tools & method
    md += ["## Tools & method", ""]
    for s in steps:
        mark = " ⟵ flag" if s.get("flags") else ""
        md.append(f"- `{s['step']}` — {s.get('summary','')}{mark}")
    md.append("")

    # Takeaways
    md += ["## Takeaways", "",
           f"- Category: **{cat}**.",
           "- KRYPT front-loaded deterministic triage; "
           + ("the winning step was " + f"`{win['step']}`." if win
              else "escalation was required."), ""]
    md += ["---", "_Generated by KRYPT — deterministic writeup, no AI tokens used._"]
    return "\n".join(md)


def add_solve(event_name: str, res: dict, flag: str, engine: str = "triage",
              event_id: str = "") -> dict:
    """Save a solved challenge (+ writeup) under an event. De-dupes by flag."""
    ev = ensure_event(event_name, event_id)
    data = _load()
    ev = next(e for e in data["events"] if e["id"] == ev["id"])
    if any(s.get("flag") == flag for s in ev["solves"]):
        return {"event_id": ev["id"], "duplicate": True}

    solve_id = uuid.uuid4().hex[:12]
    os.makedirs(WRITEUPS, exist_ok=True)
    writeup = make_writeup(res, flag, ev["name"])
    with open(os.path.join(WRITEUPS, solve_id + ".md"), "w") as fh:
        fh.write(writeup)

    t = res.get("target", {})
    ev["solves"].append({
        "id": solve_id, "ts": _now(),
        "target": t.get("raw", ""),
        "category": t.get("subkind") or t.get("kind") or "?",
        "flag": flag, "engine": engine,
    })
    _save(data)
    return {"event_id": ev["id"], "solve_id": solve_id, "duplicate": False}


def get_writeup(solve_id: str) -> str:
    if not re.fullmatch(r"[0-9a-f]{6,32}", solve_id or ""):
        return ""
    try:
        with open(os.path.join(WRITEUPS, solve_id + ".md")) as fh:
            return fh.read()
    except OSError:
        return ""


def delete_event(event_id: str) -> bool:
    data = _load()
    n = len(data["events"])
    for e in data["events"]:
        if e["id"] == event_id:
            for s in e["solves"]:
                try:
                    os.remove(os.path.join(WRITEUPS, s["id"] + ".md"))
                except OSError:
                    pass
    data["events"] = [e for e in data["events"] if e["id"] != event_id]
    _save(data)
    return len(data["events"]) < n
